language: node_js

node_js:
  - node
  - '12'
  - '10'
  - '8'

before_install:
  # Build Csound.
  - sudo apt-get --assume-yes install libsndfile1-dev
  - wget https://github.com/csound/csound/archive/6.13.0.tar.gz
  - tar -xf 6.13.0.tar.gz
  - mkdir build
  - cd build
  - cmake -DBUILD_DSSI_OPCODES=NO ../csound-6.13.0
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
  # Get csound-api dependencies.
  - sudo apt-get --assume-yes install libboost-dev

before_script:
  - npm install --global jasmine
  - npm install jasmine-terminal-reporter
