language: node_js

node_js:
  - node
  - '9'
  - '8'
  - '6'

before_install:
  # Build Csound.
  - sudo apt-get install -y alsa libsndfile1-dev
  - wget https://github.com/csound/csound/archive/6.11.0.tar.gz
  - tar -xf 6.11.0.tar.gz
  - mkdir csound
  - cd csound
  - cmake ../csound-6.11.0
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
  # Get csound-api dependencies.
  - sudo apt-get install -y libboost-dev

before_script:
  - npm --global install jasmine
