language: node_js

node_js:
  - node
  - '8'
  - '6'
  - '4'

before_install:
  - sudo apt-get build-dep csound
  - wget https://github.com/csound/csound/archive/6.09.1.tar.gz
  - tar -xf 6.09.1.tar.gz
  - mkdir csound
  - cd csound
  - cmake ../csound-6.09.1
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..

before_script:
  - npm --global install jasmine
