language: node_js

node_js:
  - node
  - "6"
  - "4"

dist: trusty

before_install:
  - sudo apt-get install -y libboost-dev libsndfile1-dev
  - wget https://github.com/csound/csound/archive/6.09.0.tar.gz
  - tar -xzf 6.09.0.tar.gz
  - mkdir csound
  - pushd csound && cmake ../csound-6.09.0 && make && sudo make install && sudo ldconfig && popd

before_script:
  - npm --global install jasmine
