language: node_js

node_js:
  - node
  - '10'
  - '8'

before_install:
  # Build Csound.
  - sudo apt-get --assume-yes install libsndfile1-dev
  - wget https://github.com/csound/csound/archive/6.13.0.tar.gz
  - tar -xf 6.13.0.tar.gz
  - mkdir build
  - cd build
  # When built with DSSI <http://dssi.sourceforge.net> opcodes, attempting to
  # produce sound from Csound 6.10.0 and later on Travis CI results in a
  # segmentation fault (see https://github.com/csound/csound/issues/901).
  - cmake -DBUILD_DSSI_OPCODES=NO ../csound-6.13.0
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
  # Get csound-api dependencies.
  - sudo apt-get --assume-yes install libboost-dev

before_script:
  - npm install --global jasmine
