language: node_js

node_js:
  - node
  - '10'
  - '8'
  - '6'

before_install:
  # Build Csound.
  - sudo apt-get install -y libsndfile1-dev
  - wget https://github.com/csound/csound/archive/6.12.0.tar.gz
  - tar -xf 6.12.0.tar.gz
  - mkdir csound
  - cd csound
  # When built with DSSI <http://dssi.sourceforge.net> opcodes, attempting to
  # produce sound from Csound 6.10.0 and later on Travis CI results in a
  # segmentation fault (see https://github.com/csound/csound/issues/901).
  - cmake -D BUILD_DSSI_OPCODES=0 ../csound-6.12.0
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
  # Get csound-api dependencies.
  - sudo apt-get install -y libboost-dev

before_script:
  - npm --global install jasmine
