language: node_js

node_js:
  - node
  - '8'
  - '6'
  - '4'

before_install:
  # Build Csound.
  - sudo apt-get install -y libsndfile1-dev
  - wget https://github.com/csound/csound/archive/6.10.0.tar.gz
  - tar -xf 6.10.0.tar.gz
  - mkdir csound
  - cd csound
  - cmake ../csound-6.10.0
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
  # Get csound-api dependencies.
  - sudo apt-get install -y libboost-dev

before_script:
  - npm --global install jasmine
